addons:
  apt:
    packages:
    - libcunit1-dev
    - clang
    - gcc-multilib

sudo: false

before_script:
  - wget http://downloads.sourceforge.net/project/cunit/CUnit/2.1-3/CUnit-2.1-3.tar.bz2 -O /tmp/cunit.tar.bz2
  - tar -xvf /tmp/cunit.tar.bz2
  - cd CUnit-2.1-3
  - CFLAGS="-m32" LDFLAGS="-m32" ./bootstrap
  - make
  - export LD_LIBRARY_PATH=$PWD/CUnit/Sources/.libs/:$LD_LIBRARY_PATH
  - cd ..

script:
    - make
    - CC=clang CFLAGS="-g -O0 -fsanitize=address" LDFLAGS="-g -fsanitize=address" make clean test
    - CFLAGS="-m32" LDFLAGS="-m32 -L$PWD/CUnit-2.1-3/CUnit/Sources/.libs/" make clean test
